#define TENTATWO_BUTTON_0 0
#define TENTATWO_BUTTON_1 1
#define TENTATWO_BUTTON_2 2
#define TENTATWO_BUTTON_3 3
#define TENTATWO_BUTTON_4 4
#define TENTATWO_BUTTON_5 5
#define TENTATWO_BUTTON_6 6
#define TENTATWO_BUTTON_7 7
